import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { courseGuides, courseLessons, type CourseLesson, type Guide, type GuideStyle } from "../data/lessonPath";

const notesStorageKey = "sip-studies-lesson-notes-v1";

function loadStoredNotes() {
  if (typeof window === "undefined") {
    return {} as Record<string, string>;
  }

  try {
    const raw = window.localStorage.getItem(notesStorageKey);
    if (!raw) {
      return {} as Record<string, string>;
    }
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === "object") {
      return parsed as Record<string, string>;
    }
  } catch {
    // Ignore parse failures and start with empty notes.
  }

  return {} as Record<string, string>;
}

function activityLabel(type: CourseLesson["type"]) {
  if (type === "video") return "Signal";
  if (type === "exercise") return "Drill";
  return "Launch";
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderList(items: string[]) {
  return `<ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

function renderTerms(lesson: CourseLesson) {
  return `
    <table>
      <thead>
        <tr><th>Term</th><th>Definition</th></tr>
      </thead>
      <tbody>
        ${lesson.keyTerms
          .map((term) => `<tr><td>${escapeHtml(term.term)}</td><td>${escapeHtml(term.definition)}</td></tr>`)
          .join("")}
      </tbody>
    </table>
  `;
}

function openPrintableDocument(title: string, contentHtml: string) {
  const popup = window.open("", "_blank", "noopener,noreferrer,width=1024,height=768");
  if (!popup) {
    return false;
  }

  popup.document.write(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #1d2733; margin: 32px; line-height: 1.45; }
    h1, h2, h3 { margin: 0 0 10px; color: #10263c; }
    h1 { font-size: 28px; }
    h2 { margin-top: 22px; font-size: 20px; border-bottom: 1px solid #d7e0e7; padding-bottom: 6px; }
    p { margin: 0 0 10px; }
    ul { margin: 8px 0 14px 18px; padding: 0; }
    li { margin: 0 0 6px; }
    pre { white-space: pre-wrap; background: #f4f7fa; padding: 12px; border-radius: 8px; border: 1px solid #d7e0e7; }
    .meta { color: #3a556e; margin-bottom: 16px; font-weight: 700; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #d7e0e7; text-align: left; padding: 8px; vertical-align: top; }
    th { background: #f0f5f8; }
    .fine { margin-top: 18px; font-size: 12px; color: #4c5d6b; }
  </style>
</head>
<body>
  ${contentHtml}
  <p class="fine">Generated by Sip Studies printable export.</p>
</body>
</html>`);
  popup.document.close();
  popup.focus();
  setTimeout(() => popup.print(), 160);
  return true;
}

function referencePacketHtml(lesson: CourseLesson, mentor: Guide) {
  return `
    <h1>${escapeHtml(lesson.title)}</h1>
    <p class="meta">Lesson ${lesson.sequence} • ${escapeHtml(lesson.chapter)} • ${lesson.minutes} minutes • Mentor: ${escapeHtml(mentor.name)}</p>
    <p>${escapeHtml(lesson.summary)}</p>
    <h2>Objectives</h2>
    ${renderList(lesson.objectives)}
    <h2>Key Concepts</h2>
    ${renderList(lesson.keyConcepts)}
    <h2>Walkthrough</h2>
    ${renderList(lesson.walkthrough)}
    <h2>Practice</h2>
    ${renderList(lesson.practice)}
    <h2>Deliverables</h2>
    ${renderList(lesson.deliverables)}
    <h2>Reflection Prompts</h2>
    ${renderList(lesson.reflection)}
    <h2>Prompt Template</h2>
    <pre>${escapeHtml(lesson.promptTemplate)}</pre>
    <h2>Key Terms</h2>
    ${renderTerms(lesson)}
    <h2>Completion Checklist</h2>
    ${renderList(lesson.printChecklist)}
  `;
}

function notesPacketHtml(lesson: CourseLesson, mentor: Guide, notes: string) {
  const noteContent = notes.trim().length > 0 ? escapeHtml(notes) : "No notes captured yet.";
  return `
    <h1>${escapeHtml(lesson.title)} - Personal Notes</h1>
    <p class="meta">Lesson ${lesson.sequence} • ${escapeHtml(lesson.chapter)} • Mentor: ${escapeHtml(mentor.name)}</p>
    <h2>Personal Notes</h2>
    <pre>${noteContent}</pre>
    <h2>Reflection Prompts</h2>
    ${renderList(lesson.reflection)}
  `;
}

function accessoryForStyle(style: GuideStyle) {
  if (style === "visor") {
    return <rect className="portrait-gear" x="19.5" y="18.5" width="25" height="8.5" rx="4.25" />;
  }

  if (style === "antenna") {
    return (
      <>
        <line className="portrait-gear-line" x1="32" y1="6.5" x2="32" y2="12" />
        <circle className="portrait-gear" cx="32" cy="5" r="2.2" />
      </>
    );
  }

  if (style === "halo") {
    return <ellipse className="portrait-gear-line" cx="32" cy="9.5" rx="13.5" ry="4.5" />;
  }

  if (style === "scanner") {
    return (
      <>
        <circle className="portrait-gear-line" cx="26" cy="22" r="4.6" />
        <line className="portrait-gear-line" x1="30.4" y1="22" x2="36.2" y2="22" />
      </>
    );
  }

  if (style === "orbital") {
    return <ellipse className="portrait-gear-line" cx="32" cy="22" rx="16.5" ry="8.2" />;
  }

  return <path className="portrait-gear" d="m32 8.2 2.3 4.1 4.3.6-3.1 3 0.7 4.1-4.2-2.2-4.2 2.2 0.7-4.1-3.1-3 4.3-.6z" />;
}

function GuidePortrait({ guide, compact = false }: { guide: Guide; compact?: boolean }) {
  const gradientId = `${guide.id}-${compact ? "compact" : "full"}-bg`;
  const cssVars = {
    "--guide-a": guide.palette[0],
    "--guide-b": guide.palette[1],
    "--guide-accent": guide.accent
  } as CSSProperties;

  return (
    <svg
      className={`guide-portrait ${compact ? "compact" : ""}`}
      viewBox="0 0 64 64"
      style={cssVars}
      role="img"
      aria-label={`${guide.name} guide avatar`}
    >
      <defs>
        <linearGradient id={gradientId} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="var(--guide-a)" />
          <stop offset="100%" stopColor="var(--guide-b)" />
        </linearGradient>
      </defs>
      <rect x="1" y="1" width="62" height="62" rx="18" fill={`url(#${gradientId})`} />
      <circle className="portrait-face" cx="32" cy="22" r="11.5" />
      {accessoryForStyle(guide.style)}
      <circle className="portrait-eye" cx="27.6" cy="22.4" r="1.5" />
      <circle className="portrait-eye" cx="36.4" cy="22.4" r="1.5" />
      <path className="portrait-smile" d="M27.2 27.1c1.2 1.3 2.8 2 4.8 2s3.6-.7 4.8-2" />
      <rect className="portrait-body" x="18" y="36" width="28" height="20" rx="10" />
    </svg>
  );
}

function LessonGlyph({ type }: { type: CourseLesson["type"] }) {
  if (type === "video") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect x="4" y="5" width="16" height="12" rx="3" />
        <path d="M10 9.25 14.8 12 10 14.75z" />
        <path d="M7.5 19h9" />
      </svg>
    );
  }

  if (type === "exercise") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <circle cx="8" cy="8" r="2.4" />
        <circle cx="16" cy="8" r="2.4" />
        <circle cx="8" cy="16" r="2.4" />
        <path d="M10.2 8h3.6M8 10.2v3.6M10 14.2l4-4" />
      </svg>
    );
  }

  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M12 4 14.8 9.3 20 11l-4.3 3.1.2 5.1L12 16.5 8.1 19.2l.2-5.1L4 11l5.2-1.7z" />
      <path d="M12 9.8v4.8M9.7 12.2h4.6" />
    </svg>
  );
}

export function LearningPath() {
  const [selectedLessonId, setSelectedLessonId] = useState(courseLessons[0]?.id ?? "");
  const [visitedLessonIds, setVisitedLessonIds] = useState<string[]>(courseLessons[0] ? [courseLessons[0].id] : []);
  const [notesByLesson, setNotesByLesson] = useState<Record<string, string>>(loadStoredNotes);
  const [exportMessage, setExportMessage] = useState("");
  const [isLessonModalOpen, setIsLessonModalOpen] = useState(false);
  const lanePattern = [0, 56, 96, 56, 0];

  const lessonById = useMemo(() => new Map(courseLessons.map((lesson) => [lesson.id, lesson])), []);
  const guideById = useMemo(() => new Map(courseGuides.map((guide) => [guide.id, guide])), []);

  const selectedLesson = lessonById.get(selectedLessonId) ?? courseLessons[0];
  const selectedGuide = selectedLesson ? guideById.get(selectedLesson.guideId) ?? courseGuides[0] : courseGuides[0];
  const notesValue = selectedLesson ? notesByLesson[selectedLesson.id] ?? "" : "";

  useEffect(() => {
    window.localStorage.setItem(notesStorageKey, JSON.stringify(notesByLesson));
  }, [notesByLesson]);

  useEffect(() => {
    if (!isLessonModalOpen) {
      return;
    }

    const previousOverflow = document.body.style.overflow;
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        setIsLessonModalOpen(false);
        setExportMessage("");
      }
    };

    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", handleKeyDown);

    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [isLessonModalOpen]);

  const openLesson = (lessonId: string) => {
    setSelectedLessonId(lessonId);
    setVisitedLessonIds((current) => (current.includes(lessonId) ? current : [...current, lessonId]));
    setIsLessonModalOpen(true);
    setExportMessage("");
  };

  const closeLessonModal = () => {
    setIsLessonModalOpen(false);
    setExportMessage("");
  };

  const exportReferencePdf = () => {
    if (!selectedLesson) return;
    const ok = openPrintableDocument(
      `${selectedLesson.title} Reference`,
      referencePacketHtml(selectedLesson, selectedGuide)
    );
    setExportMessage(ok ? "Reference packet opened in print dialog for PDF download." : "Enable popups to export PDF.");
  };

  const exportNotesPdf = () => {
    if (!selectedLesson) return;
    const ok = openPrintableDocument(
      `${selectedLesson.title} Notes`,
      notesPacketHtml(selectedLesson, selectedGuide, notesValue)
    );
    setExportMessage(ok ? "Notes export opened in print dialog for PDF download." : "Enable popups to export PDF.");
  };

  if (!selectedLesson) {
    return null;
  }

  return (
    <section className="path-section">
      <div className="section-header">
        <h2>AI course path (first 20 lessons)</h2>
        <p>Every node is clickable. Open a lesson in a full-screen workspace, study the reference packet, and keep your own notes.</p>
      </div>

      <div className="path-shell">
        <aside className="guide-deck" aria-label="Hero guides">
          <div className="guide-deck-header">
            <h3>Hero Guide Crew</h3>
            <p>Each guide mentors a different skill stack across the 20-lesson journey.</p>
          </div>
          {courseGuides.map((guide) => (
            <article className="guide-card" key={guide.id}>
              <GuidePortrait guide={guide} />
              <div>
                <p className="guide-role">{guide.role}</p>
                <h4>{guide.name}</h4>
                <p className="guide-note">{guide.note}</p>
                <p className="guide-focus">{guide.focus}</p>
              </div>
            </article>
          ))}
        </aside>

        <div className="path-main">
          <div className="path-map" aria-label="Course roadmap">
            <ol className="path-lane">
              {courseLessons.map((lesson, index) => {
                const mentor = guideById.get(lesson.guideId) ?? courseGuides[0];
                const offset = lanePattern[index % lanePattern.length];
                const isCurrent = lesson.id === selectedLesson.id;
                const isVisited = visitedLessonIds.includes(lesson.id);
                const state = isCurrent ? "current" : isVisited ? "done" : "upcoming";

                return (
                  <li
                    key={lesson.id}
                    className={`path-node ${state}`}
                    style={{ "--offset": `${offset}px` } as CSSProperties}
                  >
                    <button
                      type="button"
                      className="path-node-button"
                      onClick={() => openLesson(lesson.id)}
                      aria-current={isCurrent ? "step" : undefined}
                    >
                      <div className="node-orb" aria-hidden="true">
                        <LessonGlyph type={lesson.type} />
                      </div>

                      <div className="node-copy">
                        <p className="node-level">
                          Lesson {String(lesson.sequence).padStart(2, "0")} - {lesson.chapter}
                        </p>
                        <h4>{lesson.title}</h4>
                        <p>{lesson.summary}</p>
                        <div className="node-mentor">
                          <GuidePortrait guide={mentor} compact />
                          <strong>{mentor.name}</strong>
                          <span>{mentor.focus}</span>
                        </div>
                        <p className="node-meta">
                          {activityLabel(lesson.type)} mode - {lesson.minutes} minutes
                        </p>
                      </div>
                    </button>
                  </li>
                );
              })}
            </ol>
          </div>


        </div>
      {isLessonModalOpen ? (
        <div className="lesson-modal-overlay" onClick={closeLessonModal}>
          <article
            className="lesson-modal"
            role="dialog"
            aria-modal="true"
            aria-label={`Lesson ${String(selectedLesson.sequence).padStart(2, "0")} workspace`}
            onClick={(event) => event.stopPropagation()}
          >
            <header className="lesson-modal-topbar">
              <p className="lesson-modal-title">
                Lesson {String(selectedLesson.sequence).padStart(2, "0")} workspace
              </p>
              <button
                className="btn btn-light lesson-modal-close"
                type="button"
                onClick={closeLessonModal}
                aria-label="Close lesson workspace"
              >
                Escape (Esc)
              </button>
            </header>

            <section className="lesson-studio lesson-modal-studio" aria-label="Lesson workspace">
              <article className="lesson-content">
                <header className="lesson-header">
                  <p className="lesson-chip">
                    Lesson {String(selectedLesson.sequence).padStart(2, "0")} - {selectedLesson.chapter}
                  </p>
                  <h3>{selectedLesson.title}</h3>
                  <p>{selectedLesson.summary}</p>
                  <div className="lesson-meta-row">
                    <span>{selectedLesson.minutes} min</span>
                    <span>{activityLabel(selectedLesson.type)} mode</span>
                    <span>Mentor: {selectedGuide.name}</span>
                  </div>
                  <div className="lesson-actions">
                    <button className="btn btn-primary" type="button" onClick={exportReferencePdf}>
                      Download Reference PDF
                    </button>
                    <button className="btn btn-light" type="button" onClick={exportNotesPdf}>
                      Export My Notes PDF
                    </button>
                  </div>
                  {exportMessage ? <p className="hint">{exportMessage}</p> : null}
                </header>

                <div className="lesson-block">
                  <h4>Objectives</h4>
                  <ul>
                    {selectedLesson.objectives.map((item) => (
                      <li key={`objective-${item}`}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="lesson-block">
                  <h4>Key Concepts</h4>
                  <ul>
                    {selectedLesson.keyConcepts.map((item) => (
                      <li key={`concept-${item}`}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="lesson-block">
                  <h4>Walkthrough</h4>
                  <ol>
                    {selectedLesson.walkthrough.map((item) => (
                      <li key={`walk-${item}`}>{item}</li>
                    ))}
                  </ol>
                </div>

                <div className="lesson-block">
                  <h4>Practice Sprint</h4>
                  <ul>
                    {selectedLesson.practice.map((item) => (
                      <li key={`practice-${item}`}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="lesson-block">
                  <h4>Deliverables</h4>
                  <ul>
                    {selectedLesson.deliverables.map((item) => (
                      <li key={`deliverable-${item}`}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="lesson-block">
                  <h4>Prompt Template</h4>
                  <pre>{selectedLesson.promptTemplate}</pre>
                </div>

                <div className="lesson-block">
                  <h4>Reflection Prompts</h4>
                  <ul>
                    {selectedLesson.reflection.map((item) => (
                      <li key={`reflect-${item}`}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="lesson-block">
                  <h4>Printable Key Terms</h4>
                  <table className="lesson-terms">
                    <thead>
                      <tr>
                        <th>Term</th>
                        <th>Definition</th>
                      </tr>
                    </thead>
                    <tbody>
                      {selectedLesson.keyTerms.map((term) => (
                        <tr key={`${term.term}-${term.definition}`}>
                          <td>{term.term}</td>
                          <td>{term.definition}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </article>

              <aside className="lesson-notes">
                <h4>Personal notes</h4>
                <p className="hint">Write freely. Notes auto-save in this browser per lesson.</p>
                <textarea
                  value={notesValue}
                  onChange={(event) =>
                    setNotesByLesson((current) => ({
                      ...current,
                      [selectedLesson.id]: event.target.value
                    }))
                  }
                  placeholder="Capture takeaways, examples, prompts to reuse, and action items."
                  rows={20}
                />
                <p className="notes-meta">{notesValue.length} characters</p>
                <div className="notes-actions">
                  <button className="btn btn-light" type="button" onClick={exportNotesPdf}>
                    Export Notes PDF
                  </button>
                  <button
                    className="btn btn-light"
                    type="button"
                    onClick={() =>
                      setNotesByLesson((current) => ({
                        ...current,
                        [selectedLesson.id]: ""
                      }))
                    }
                  >
                    Clear Notes
                  </button>
                </div>
              </aside>
            </section>
          </article>
        </div>
      ) : null}
      </div>
    </section>
  );
}


