-- Rewrite terminology meanings with original professional beverage definitions and shelf citations.
-- Definitions are original Sip Studies editorial text, informed by credited reference works, with no verbatim excerpts.

with reference_shelf as (
  select
    array['https://www.amazon.com/s?k=Karen+MacNeil+The+Wine+Bible', 'https://www.amazon.com/s?k=Hugh+Johnson+Jancis+Robinson+World+Atlas+of+Wine', 'https://www.amazon.com/s?k=Garrett+Oliver+Oxford+Companion+to+Beer', 'https://www.amazon.com/s?k=Oxford+Companion+to+Spirits+and+Cocktails', 'https://www.amazon.com/s?k=James+Hoffmann+World+Atlas+of+Coffee', 'https://www.amazon.com/s?k=Tea+History+Terroirs+Varieties+Kevin+Gascoyne', 'https://www.amazon.com/s?k=Hannah+Crum+Alex+LaGory+Big+Book+of+Kombucha', 'https://www.amazon.com/s?k=Harold+McGee+On+Food+and+Cooking', 'https://www.amazon.com/s?k=Michael+Mascha+Fine+Waters']::text[] as reference_links,
    array['MacNeil, Karen. The Wine Bible. 3rd ed., Workman Publishing, 2022.', 'Johnson, Hugh, and Jancis Robinson. The World Atlas of Wine. 8th ed., Mitchell Beazley, 2019.', 'Oliver, Garrett, editor. The Oxford Companion to Beer. Oxford University Press, 2011.', 'Wondrich, David, and Noah Rothbaum, editors. The Oxford Companion to Spirits and Cocktails. Oxford University Press, 2021.', 'Hoffmann, James. The World Atlas of Coffee. Mitchell Beazley.', 'Gascoyne, Kevin, Francois Marchand, Jasmin Desharnais, and Hugo Americi. Tea: History, Terroirs, Varieties. Firefly Books, 2014.', 'Crum, Hannah, and Alex LaGory. The Big Book of Kombucha. Storey Publishing, 2016.', 'McGee, Harold. On Food and Cooking: The Science and Lore of the Kitchen. Scribner, 2004.', 'Mascha, Michael. Fine Waters: A Connoisseur''s Guide to the World''s Most Distinctive Bottled Waters. Quench Ventures, 2013.']::text[] as mla_citations,
    'Sip Studies Original Editorial Glossary Curated v3'::text as source_title,
    array['Sip Studies Editorial Team']::text[] as source_authors,
    array['https://www.amazon.com/s?k=Karen+MacNeil+The+Wine+Bible', 'https://www.amazon.com/s?k=Hugh+Johnson+Jancis+Robinson+World+Atlas+of+Wine', 'https://www.amazon.com/s?k=Garrett+Oliver+Oxford+Companion+to+Beer', 'https://www.amazon.com/s?k=Oxford+Companion+to+Spirits+and+Cocktails', 'https://www.amazon.com/s?k=James+Hoffmann+World+Atlas+of+Coffee', 'https://www.amazon.com/s?k=Tea+History+Terroirs+Varieties+Kevin+Gascoyne', 'https://www.amazon.com/s?k=Hannah+Crum+Alex+LaGory+Big+Book+of+Kombucha', 'https://www.amazon.com/s?k=Harold+McGee+On+Food+and+Cooking', 'https://www.amazon.com/s?k=Michael+Mascha+Fine+Waters']::text[] as purchase_links,
    'Original editorial paraphrase informed by credited reference works; no verbatim source language used.'::text as source_rights_basis,
    'Original Sip Studies glossary definition written from scratch in a professional beverage style and supported by the shared reference shelf documented in docs/terminology_reference_shelf.md.'::text as source_note
), defs(term, beverage_type, meaning) as (
  values
    ('Adjunct', 'beer', 'An adjunct is any fermentable or functional brewing ingredient used alongside malted grain to modify body flavor color yield or process performance.'),
    ('Ale', 'beer', 'Ale is beer fermented primarily with top-fermenting yeast at relatively warm temperatures producing a broad range of ester-driven profiles.'),
    ('Altbier', 'beer', 'Altbier is a traditional German amber ale from Dusseldorf brewed with ale yeast and conditioned cold for a clean firm finish.'),
    ('Amber', 'beer', 'Amber describes beer with a copper to reddish-gold color typically derived from kilned or lightly caramelized malts.'),
    ('Amylase', 'beer', 'Amylase is the enzyme group that breaks starch into fermentable sugars and dextrins during malting and mashing.'),
    ('Attenuation', 'beer', 'Attenuation is the percentage of wort sugars consumed by yeast and indicates how dry or full-bodied a beer finishes.'),
    ('Barleywine', 'beer', 'Barleywine is a very strong malt-forward ale or lager with elevated alcohol concentration rich body and substantial aging potential.'),
    ('Berlinerweisse', 'beer', 'Berlinerweisse is a pale low-alcohol wheat beer defined by high carbonation bright acidity and a lean refreshing structure.'),
    ('Bitterness', 'beer', 'Bitterness is the taste impression created mainly by iso-alpha acids and other compounds that balance malt sweetness in beer.'),
    ('Bock', 'beer', 'Bock is a strong German lager family known for pronounced malt depth restrained hop character and smooth alcohol integration.'),
    ('Brett', 'beer', 'Brett is shorthand for Brettanomyces which is a yeast genus that can create earthy fruity leathery or funky fermentation character.'),
    ('Brut', 'beer', 'Brut describes an extremely dry beer style or variant brewed to leave minimal residual sugar and a crisp sparkling finish.'),
    ('Cascade', 'beer', 'Cascade is an American hop variety known for grapefruit citrus floral notes and its foundational role in modern pale ales.'),
    ('Cask', 'beer', 'Cask refers to beer conditioned and served from a container where natural carbonation develops without extraneous gas for dispense.'),
    ('Centennial', 'beer', 'Centennial is an American hop variety prized for concentrated citrus floral and resinous aromas with solid bittering capability.'),
    ('Chinook', 'beer', 'Chinook is an American hop variety that contributes assertive pine grapefruit spice and firm bitterness to hop-forward beers.'),
    ('Citra', 'beer', 'Citra is a modern American hop variety valued for intense tropical fruit lime citrus and aromatic saturation in late hopping.'),
    ('Columbus', 'beer', 'Columbus is a high-alpha American hop used for pungent resinous aroma and assertive bitterness in many robust styles.'),
    ('Conditioning', 'beer', 'Conditioning is the maturation phase after primary fermentation when beer clarifies carbonates stabilizes and integrates flavor compounds.'),
    ('Decoction', 'beer', 'Decoction is a mash method where part of the mash is boiled and returned to raise temperature and intensify malt character.'),
    ('Dextrin', 'beer', 'Dextrin is a relatively unfermentable carbohydrate that contributes fullness viscosity and residual body to finished beer.'),
    ('Diacetyl', 'beer', 'Diacetyl is a vicinal diketone that gives beer a butter or butterscotch aroma and is usually considered a fermentation flaw.'),
    ('Dortmunder', 'beer', 'Dortmunder is a pale German export lager with balanced bitterness firm minerality and a fuller malt profile than standard pilsner.'),
    ('Dryhopping', 'beer', 'Dryhopping is the addition of hops after or near the end of fermentation to increase aroma with little added bitterness.'),
    ('Dunkel', 'beer', 'Dunkel is a dark German lager emphasizing bread crust toast and smooth malt richness rather than roasted intensity.'),
    ('Ebc', 'beer', 'EBC is the European Brewery Convention color scale used to quantify beer and wort color analytically.'),
    ('Ester', 'beer', 'Ester is a fermentation-derived aroma compound that commonly expresses fruit notes such as pear banana apple or stone fruit.'),
    ('Fermentor', 'beer', 'A fermentor is the vessel where yeast converts wort sugars into alcohol carbon dioxide and a wide range of flavor compounds.'),
    ('Flocculation', 'beer', 'Flocculation is the tendency of yeast cells to clump together and settle from suspension near the end of fermentation.'),
    ('Fuggles', 'beer', 'Fuggles is a classic English hop variety associated with earthy woody herbal aromas and soft traditional bitterness.'),
    ('Gueuze', 'beer', 'Gueuze is a blended spontaneous-fermentation beer made by combining young and aged lambic for bottle refermentation complexity and dryness.'),
    ('Hallertau', 'beer', 'Hallertau refers to classic German noble hop types known for delicate floral herbal and spicy aromas with restrained bitterness.'),
    ('Haze', 'beer', 'Haze is visible turbidity in beer caused by suspended yeast proteins polyphenols starch or other particulate matter.'),
    ('Hefeweizen', 'beer', 'Hefeweizen is an unfiltered German wheat ale recognized for high carbonation cloudy appearance and yeast-driven banana and clove character.'),
    ('Helles', 'beer', 'Helles is a pale Munich lager with soft malt expression gentle bitterness and a clean highly drinkable finish.'),
    ('Hopback', 'beer', 'A hopback is a vessel that passes hot wort through hops after the kettle to capture aroma and filter solids.'),
    ('Hopstand', 'beer', 'Hopstand is a post-boil steep where hops remain in hot wort to extract flavor and aroma with moderated bitterness.'),
    ('Hydrometer', 'beer', 'A hydrometer is a floating instrument that measures liquid density to estimate wort sugar concentration and fermentation progress.'),
    ('Ibu', 'beer', 'IBU means International Bitterness Units and measures the concentration of iso-alpha acids associated with perceived beer bitterness.'),
    ('Infusion', 'beer', 'Infusion is a mash technique that reaches target rests by adding heated water instead of boiling part of the mash.'),
    ('Isomerization', 'beer', 'Isomerization is the heat-driven conversion of hop alpha acids into more soluble iso-alpha acids during wort boiling.'),
    ('Kolsch', 'beer', 'Kolsch is a pale delicately fruity German ale from Cologne that is cold conditioned and drinks with lager-like crispness.'),
    ('Krausen', 'beer', 'Krausen is the foamy yeast-rich head that forms during active fermentation and indicates vigorous carbon dioxide evolution.'),
    ('Lactobacillus', 'beer', 'Lactobacillus is a lactic acid bacterium used intentionally in sour beer production or encountered as a spoilage organism.'),
    ('Lager', 'beer', 'Lager is beer fermented with bottom-fermenting yeast and matured cold to produce a clean stable and polished profile.'),
    ('Lambic', 'beer', 'Lambic is a Belgian wheat-based beer produced through spontaneous fermentation and extended maturation in wood or stainless vessels.'),
    ('Lauter', 'beer', 'Lauter means separating sweet wort from the spent grain bed after mashing usually in a lauter tun or mash filter.'),
    ('Lovibond', 'beer', 'Lovibond is a traditional color scale used to classify malt and beer color though analytical standards now often use SRM or EBC.'),
    ('Malt', 'beer', 'Malt is grain that has been steeped germinated and kilned to develop enzymes fermentable extract color and characteristic flavor.'),
    ('Mash', 'beer', 'Mash is the mixture of crushed malt and hot water where enzymes convert starches into soluble sugars for brewing.'),
    ('Mosaic', 'beer', 'Mosaic is an American hop variety known for layered berry tropical citrus and resin notes with high aromatic intensity.'),
    ('Pasteurization', 'beer', 'Pasteurization is controlled heat treatment applied to beer to reduce microbial load and improve package stability.'),
    ('Phenolic', 'beer', 'Phenolic describes clove-like spicy smoky medicinal or plastic-like aromas created by certain yeast strains or contamination.'),
    ('Pilsner', 'beer', 'Pilsner is a pale lager style noted for bright hop bitterness crisp fermentation profile and a highly attenuated finish.'),
    ('Plato', 'beer', 'Plato is a density scale that expresses the percentage of dissolved extract in wort by weight.'),
    ('Porter', 'beer', 'Porter is a dark beer style built on chocolate toast caramel and moderate roast character with medium to full body.'),
    ('Priming', 'beer', 'Priming is the addition of fermentable sugar before packaging to generate carbonation through secondary fermentation in the sealed container.'),
    ('Reinheitsgebot', 'beer', 'Reinheitsgebot is the historic German beer purity law that restricted brewing materials and influenced later legal standards.'),
    ('Saaz', 'beer', 'Saaz is a Czech noble hop variety known for delicate earthy herbal spicy aroma and refined bitterness.'),
    ('Saison', 'beer', 'Saison is a highly attenuated farmhouse ale that often shows peppery phenolics fruity esters and a dry expressive finish.'),
    ('Sediment', 'beer', 'Sediment is the layer of settled yeast protein hop matter or other solids that collects in beer during storage.'),
    ('Simcoe', 'beer', 'Simcoe is an American hop variety valued for pine passion fruit citrus and dank aromatic character across many modern styles.'),
    ('Sparge', 'beer', 'To sparge is to rinse the grain bed with hot water to recover remaining extract after wort runoff begins.'),
    ('Stout', 'beer', 'Stout is a dark beer style defined by roasted malt character that can range from dry and bitter to rich and sweet.'),
    ('Tettnang', 'beer', 'Tettnang is a German noble hop variety prized for subtle floral herbal and peppery aroma in lagers and wheat beers.'),
    ('Trappist', 'beer', 'Trappist describes beer brewed under monastic supervision within a Trappist abbey according to association production standards.'),
    ('Trub', 'beer', 'Trub is the mass of coagulated proteins hop particles lipids and other solids separated from wort or young beer.'),
    ('Whirlpool', 'beer', 'Whirlpool is the circular separation step that concentrates hot break and hop solids into a central cone after boiling.'),
    ('Witbier', 'beer', 'Witbier is a Belgian-style wheat ale typically brewed with unmalted wheat coriander orange peel and a softly hazy appearance.'),
    ('Wort', 'beer', 'Wort is the sweet liquid extracted from the mash that contains sugars nutrients and precursors needed for fermentation.'),
    ('Aeropress', 'coffee', 'A manual brewer that uses immersion and pressure to produce a concentrated clean cup with flexible recipes.'),
    ('Aftertaste', 'coffee', 'The flavors and tactile sensations that remain in the mouth after swallowing or spitting coffee.'),
    ('Americano', 'coffee', 'An espresso drink extended with hot water to create a longer cup while retaining espresso-based flavor structure.'),
    ('Anaerobic', 'coffee', 'A fermentation approach that limits oxygen exposure to alter microbial activity and create distinctive acidity texture and aromatic intensity.'),
    ('Arabica', 'coffee', 'A coffee species valued for greater sweetness and acidity than robusta and commonly used for specialty production at higher elevations.'),
    ('Backflush', 'coffee', 'A cleaning procedure that sends water and detergent backward through the espresso group to remove coffee oils.'),
    ('Bourbon', 'coffee', 'An arabica cultivar group descended from Typica and known for sweetness balanced acidity and strong cup potential.'),
    ('Cappuccino', 'coffee', 'An espresso and milk drink built with steamed milk and foam in a balanced proportion and smaller format.'),
    ('Caramelization', 'coffee', 'The thermal breakdown of sugars during roasting that contributes sweetness bitterness color and deeper cooked sugar flavors.'),
    ('Catimor', 'coffee', 'A group of arabica hybrids bred from Caturra and Timor material for disease resistance and generally high productivity.'),
    ('Catuai', 'coffee', 'A hybrid of Mundo Novo and Caturra bred for productivity wind resistance and reliable performance in many growing regions.'),
    ('Caturra', 'coffee', 'A compact bourbon mutation that produces good cup quality and suits denser planting because of its shorter growth habit.'),
    ('Channeling', 'coffee', 'Uneven water flow through a coffee bed that over extracts some areas while under extracting others.'),
    ('Chemex', 'coffee', 'A pour-over brewer using thick paper filters that typically produce high clarity light body and low sediment.'),
    ('Cortado', 'coffee', 'An espresso drink cut with a similar volume of warm milk to soften intensity while preserving coffee flavor.'),
    ('Crema', 'coffee', 'The reddish brown foam on fresh espresso formed from emulsified oils suspended gases and fine solids.'),
    ('Cupper', 'coffee', 'A coffee professional trained to assess coffee quality through cupping and make consistent sensory judgments.'),
    ('Cupping', 'coffee', 'A standardized tasting method for evaluating coffee aroma flavor acidity body and defects across multiple samples.'),
    ('Defect', 'coffee', 'Any physical fault in green or roasted coffee that lowers quality consistency or cup cleanliness.'),
    ('Degassing', 'coffee', 'The release of carbon dioxide from roasted coffee over time which affects extraction crema and package stability.'),
    ('Demucilage', 'coffee', 'The removal of mucilage from parchment coffee by machine to reduce fermentation time and water use during washing.'),
    ('Development', 'coffee', 'The roasting phase after first crack where flavor solubility sweetness and structure are shaped before the coffee is dropped.'),
    ('Dose', 'coffee', 'The mass of dry ground coffee used for a brew or espresso shot before extraction begins.'),
    ('Dripper', 'coffee', 'A manual brew device that holds filter and grounds while water passes through by gravity into a server or cup.'),
    ('Drymill', 'coffee', 'A facility that hulls dried parchment or dried cherry and prepares green coffee through cleaning grading and bagging.'),
    ('Espresso', 'coffee', 'A concentrated coffee brewed by forcing hot water through finely ground coffee under pressure in a short extraction.'),
    ('Excelsa', 'coffee', 'A botanical type within liberica valued for tart fruit-driven character and its use adding complexity to blends.'),
    ('Fragrance', 'coffee', 'The smell of dry ground coffee before water is added and before aroma is evaluated in the wet cup.'),
    ('Frenchpress', 'coffee', 'An immersion brewer where coffee steeps in water before a metal mesh plunger separates grounds from beverage.'),
    ('Geisha', 'coffee', 'An arabica variety famous for floral aromatics tea-like structure and high market value when grown and processed well.'),
    ('Grouphead', 'coffee', 'The brewing assembly on an espresso machine that delivers water to the portafilter and stabilizes extraction conditions.'),
    ('Heirloom', 'coffee', 'A broad trade term for traditional Ethiopian coffee varieties that are often genetically diverse rather than a single cultivar.'),
    ('Honey', 'coffee', 'A processing method where some sticky mucilage remains during drying to balance fruit sweetness with cleaner structure than many naturals.'),
    ('Kalita', 'coffee', 'A flat-bottom pour-over brewer designed for even drainage and consistent extraction through small outlet holes.'),
    ('Liberica', 'coffee', 'A coffee species with large irregular beans and distinctive fruity woody flavors that differs clearly from arabica and robusta.'),
    ('Lungo', 'coffee', 'An espresso extracted to a larger beverage yield which usually increases dilution and draws more bitter compounds.'),
    ('Macchiato', 'coffee', 'An espresso marked with a small amount of milk or foam so the coffee remains the primary sensory element.'),
    ('Maillard', 'coffee', 'A browning reaction between amino compounds and sugars that builds roast aromas color and savory sweetness during coffee roasting.'),
    ('Maragogipe', 'coffee', 'An arabica mutation recognized for unusually large beans low density and variable cup quality depending on cultivation and roast.'),
    ('Mucilage', 'coffee', 'The sticky sugary layer surrounding the parchment that strongly influences fermentation drying behavior and final cup character.'),
    ('MundoNovo', 'coffee', 'A vigorous bourbon typica hybrid grown for strong productivity tall plants and dependable quality in Brazil and elsewhere.'),
    ('Natural', 'coffee', 'A processing method where whole coffee cherries dry intact so fruit contact can increase body sweetness and fermented fruit notes.'),
    ('Pacamara', 'coffee', 'A large bean hybrid of Pacas and Maragogipe often noted for high potential complexity and striking seed size.'),
    ('Portafilter', 'coffee', 'The handled metal basket assembly that holds espresso grounds and locks into the grouphead during extraction.'),
    ('Pulping', 'coffee', 'The mechanical removal of coffee cherry skin and much of the fruit before fermentation washing or drying.'),
    ('Refractometer', 'coffee', 'An optical meter that estimates dissolved coffee concentration by measuring how a liquid bends light.'),
    ('Ristretto', 'coffee', 'An espresso prepared with less output than a standard shot to emphasize concentration body and reduced bitter finish.'),
    ('Roast', 'coffee', 'The controlled application of heat to green coffee to develop aroma solubility color and flavor.'),
    ('Roastery', 'coffee', 'A production space where green coffee is profiled roasted cooled and packaged for wholesale or retail use.'),
    ('Robusta', 'coffee', 'A coffee species known for higher caffeine stronger bitterness and good disease resistance often used in blends and soluble coffee.'),
    ('Screening', 'coffee', 'A grading step that sorts green coffee by bean size using sieves with standardized hole diameters.'),
    ('Siphon', 'coffee', 'A vacuum brewer that moves water between chambers with heat and pressure changes for a clean aromatic cup.'),
    ('Sweetness', 'coffee', 'The sensory impression of sugar-like flavor balance that rounds acidity and bitterness in coffee.'),
    ('Tamper', 'coffee', 'A tool used to compress ground coffee evenly in an espresso basket to promote uniform water flow.'),
    ('Turkish', 'coffee', 'A preparation method using very fine coffee simmered in water and served unfiltered with sediment in the cup.'),
    ('Typica', 'coffee', 'One of the oldest arabica cultivars known for balanced cup quality tall trees and comparatively low yields.'),
    ('Washed', 'coffee', 'A processing method that removes fruit before drying to highlight acidity clarity and transparent expression of variety and origin.'),
    ('Wetmill', 'coffee', 'A processing site where cherries are pulped fermented washed and initially dried before later dry milling.'),
    ('Yield', 'coffee', 'The beverage mass or volume produced from a given coffee dose during brewing or espresso extraction.'),
    ('Acidulant', 'juice', 'An acid ingredient used to lower pH sharpen flavor and support microbial stability and color retention in juice beverages.'),
    ('Ascorbate', 'juice', 'The salt form of ascorbic acid used as an antioxidant to protect juice color flavor and nutritional positioning.'),
    ('Aseptic', 'juice', 'A packaging or processing method that sterilizes product and container separately before filling to achieve shelf stability without refrigeration.'),
    ('Browning', 'juice', 'The development of darker color in juice caused by enzymatic or oxidative reactions that can also alter flavor.'),
    ('Chiller', 'juice', 'Equipment that rapidly lowers juice temperature after extraction or heat treatment to protect freshness and slow microbial growth.'),
    ('Citric', 'juice', 'Citric acid is a common acidulant that adds bright tartness and helps control pH in many juice products.'),
    ('Clarifier', 'juice', 'A processing aid or system used to remove suspended material from juice and produce a cleaner brighter and more stable appearance.'),
    ('Cloudiness', 'juice', 'The visual haze created by fine suspended solids in juice that influences appearance body and consumer style expectations.'),
    ('Coldpress', 'juice', 'A juice extraction approach using mechanical pressing with minimal heat input to preserve fresh aroma color and texture.'),
    ('Color', 'juice', 'The visual appearance of juice determined by pigments processing conditions oxidation and suspended material.'),
    ('Concentrate', 'juice', 'Juice with much of its water removed to reduce volume for storage transport and later use in blending or reconstitution.'),
    ('Conveyor', 'juice', 'A mechanical transport system that moves fruit containers or finished packages through processing filling and packing operations.'),
    ('Deaeration', 'juice', 'The removal of dissolved and entrained air from juice to limit oxidation foaming and flavor loss before packaging.'),
    ('Distribution', 'juice', 'The movement of finished juice through warehouses transport and retail channels while maintaining required quality conditions.'),
    ('Enzyme', 'juice', 'A functional protein added during processing to drive specific reactions such as pectin breakdown yield improvement or haze reduction.'),
    ('Flavor', 'juice', 'The combined sensory impression from taste aroma and trigeminal effects that defines the character of a juice product.'),
    ('Hue', 'juice', 'The specific shade of juice color such as yellow orange or red used to describe visual identity and process consistency.'),
    ('Juiciness', 'juice', 'The perceived abundance of liquid released from fruit or suggested by a juice product''s aroma flavor and mouthwatering effect.'),
    ('Labeling', 'juice', 'The product identification and information applied to juice packaging including name ingredients claims dates and regulatory details.'),
    ('Mouthfeel', 'juice', 'The tactile impression of juice in the mouth including body viscosity astringency smoothness and particulate texture.'),
    ('Nectar', 'juice', 'A juice beverage made by blending fruit puree or juice with water and optional sweetening to reach a drinkable texture and balanced flavor.'),
    ('Pectinase', 'juice', 'An enzyme used to break down pectin so juice releases more easily filters faster and develops lower viscosity.'),
    ('Pomace', 'juice', 'The solid residue of skins pulp seeds and other insoluble material left after juice extraction.'),
    ('Pressing', 'juice', 'The mechanical extraction step where pressure is applied to crushed fruit or vegetables to separate liquid juice from solids.'),
    ('Pulp', 'juice', 'Small insoluble fruit particles carried in juice that add texture visual density and a more natural extraction character.'),
    ('Reconstitution', 'juice', 'The process of restoring concentrated juice to target strength by adding water and adjusting solids acid and flavor balance.'),
    ('Refreshment', 'juice', 'The sensory effect of a juice product that delivers thirst quenching appeal through temperature acidity aroma and clean finish.'),
    ('Retort', 'juice', 'A thermal process or pressure vessel used to heat sealed juice packages to commercial sterility for ambient storage.'),
    ('Ripening', 'juice', 'The maturation phase in which fruit develops higher sugar softer texture and more suitable flavor for juice extraction.'),
    ('Sedimentation', 'juice', 'The settling of suspended solids to the bottom of a package over time which signals instability or insufficient homogenization.'),
    ('Stabilizer', 'juice', 'An ingredient that helps maintain uniform texture suspension or viscosity and reduces separation during storage and distribution.'),
    ('Storage', 'juice', 'The controlled holding of raw materials bulk juice or finished packages under conditions that protect quality and safety.'),
    ('Sweetener', 'juice', 'An ingredient added to increase perceived sweetness and sometimes body while balancing acidity bitterness or dilute fruit character.'),
    ('Tartaric', 'juice', 'Tartaric acid is a naturally sharp acid used less often in juice to adjust acidity and reinforce a firm dry finish.'),
    ('Turbidity', 'juice', 'A measure of how much suspended material scatters light in juice and therefore indicates haze level and visual density.'),
    ('Acetate', 'kombucha', 'Acetate refers to the salt or ester form of acetic acid and can describe compounds contributing fruity or solvent-like notes.'),
    ('Acetic', 'kombucha', 'Acetic describes aromas or flavors reminiscent of vinegar caused mainly by acetic acid formed during aerobic fermentation.'),
    ('Acetobacter', 'kombucha', 'Acetobacter is a group of aerobic bacteria that convert ethanol into acetic acid and contribute sharp vinegar-like notes in kombucha.'),
    ('Acidification', 'kombucha', 'Acidification is the process of lowering pH through acid production which helps shape flavor and improve microbial stability.'),
    ('Backslop', 'kombucha', 'Backslop is the practice of using finished or fermenting kombucha from a previous batch to start the next batch.'),
    ('Biofilm', 'kombucha', 'A biofilm is a structured layer of microorganisms attached to a surface and embedded in a self-produced matrix.'),
    ('Brettanomyces', 'kombucha', 'Brettanomyces is a yeast genus that can generate earthy fruity or funky aromas when present in mixed fermentation beverages.'),
    ('Carbonation', 'kombucha', 'Carbonation is the dissolved carbon dioxide in a beverage that creates pressure bubbles and a lively mouthfeel.'),
    ('Cellulose', 'kombucha', 'Cellulose is the structural polysaccharide produced by certain kombucha bacteria that forms the leathery surface pellicle.'),
    ('Contamination', 'kombucha', 'Contamination is the introduction of unwanted microorganisms or foreign material that alters flavor stability safety or fermentation performance.'),
    ('Cooling', 'kombucha', 'Cooling is the controlled reduction of beverage temperature to slow microbial activity stabilize flavor and improve handling before packaging.'),
    ('Culture', 'kombucha', 'A culture is the population of microorganisms maintained and used to start or sustain fermentation in a beverage.'),
    ('Dilution', 'kombucha', 'Dilution is the reduction of concentration by adding water or another liquid which changes flavor intensity acidity and body.'),
    ('Dryness', 'kombucha', 'Dryness is the impression of low residual sugar and a less sweet finish after fermentation consumes available sugars.'),
    ('Effervescence', 'kombucha', 'Effervescence is the visible and tactile release of dissolved carbon dioxide as streams of bubbles rise in the glass.'),
    ('Ethanol', 'kombucha', 'Ethanol is the primary alcohol produced by yeast during fermentation and it serves as a precursor for acetic acid formation.'),
    ('Fizz', 'kombucha', 'Fizz is the casual term for noticeable carbonation expressed as bubble activity prickliness and audible release when opened.'),
    ('Flavoring', 'kombucha', 'Flavoring is the addition of fruits herbs spices juices or other ingredients to modify aroma taste and overall profile.'),
    ('Gluconacetobacter', 'kombucha', 'Gluconacetobacter is an acetic acid bacterium associated with kombucha that produces organic acids and the cellulose matrix of the surface pellicle.'),
    ('Gluconic', 'kombucha', 'Gluconic describes the mild acid character linked to gluconic acid which contributes soft tartness in kombucha.'),
    ('Headspace', 'kombucha', 'Headspace is the air gap between the liquid and container closure which affects oxygen exposure and carbonation development.'),
    ('Inoculum', 'kombucha', 'Inoculum is the starter liquid or culture added to a fresh batch to seed fermentation with active microbes and acidity.'),
    ('Kahm', 'kombucha', 'Kahm is a thin matte yeast film that can form on fermenting liquids and may produce stale or cheesy aromas.'),
    ('Lactic', 'kombucha', 'Lactic describes a smooth yogurt-like acidity associated with lactic acid and certain bacteria in mixed fermentation.'),
    ('Malic', 'kombucha', 'Malic describes the firm green-apple acidity associated with malic acid and a crisp tart impression on the palate.'),
    ('Mold', 'kombucha', 'Mold is a filamentous fungus that appears as fuzzy growth and indicates a spoiled culture that should be discarded.'),
    ('Pellicle', 'kombucha', 'The pellicle is the rubbery cellulose layer that forms at the liquid surface during fermentation as acetic acid bacteria build structure.'),
    ('Primary', 'kombucha', 'Primary refers to the main fermentation stage when microbes consume sweetened tea sugars and produce acids aroma compounds and some alcohol.'),
    ('Saccharomyces', 'kombucha', 'Saccharomyces is a yeast genus that ferments sugars into ethanol and carbon dioxide providing alcohol precursors and some carbonation.'),
    ('Sanitation', 'kombucha', 'Sanitation is the cleaning and disinfecting of equipment and surfaces to reduce unwanted microbes before and during production.'),
    ('Scoby', 'kombucha', 'A SCOBY is the mixed community of bacteria and yeast that ferments sweetened tea into kombucha and helps establish acidity and characteristic flavor.'),
    ('Secondary', 'kombucha', 'Secondary refers to the stage after primary fermentation when kombucha is packaged or transferred for further carbonation flavor integration or maturation.'),
    ('Sourness', 'kombucha', 'Sourness is the basic taste caused by acids and perceived as tart sharp or puckering on the palate.'),
    ('Succinic', 'kombucha', 'Succinic describes an acid-derived taste impression that can seem savory bitter or slightly salty in fermented beverages.'),
    ('Symbiosis', 'kombucha', 'Symbiosis is the cooperative relationship between yeast and bacteria where each supports fermentation through complementary metabolic activity.'),
    ('Tanginess', 'kombucha', 'Tanginess is the bright sharp taste sensation produced by balanced acidity that makes kombucha seem lively and refreshing.'),
    ('Vinegar', 'kombucha', 'Vinegar is a sour acidic liquid produced when acetic acid bacteria oxidize ethanol and it signals over-acidified kombucha when dominant.'),
    ('Bovine', 'milk', 'Bovine means derived from cattle and it describes milk or dairy products made from cow milk.'),
    ('Buffalo', 'milk', 'Buffalo milk comes from water buffalo and is typically richer in fat protein and total solids than cow milk.'),
    ('Buttermilk', 'milk', 'Buttermilk is the tangy liquid from butter making or a cultured dairy drink made to mimic that character.'),
    ('Caprine', 'milk', 'Caprine means derived from goats and it describes milk or dairy products made from goat milk.'),
    ('Casein', 'milk', 'Casein is the main milk protein family that forms micelles and strongly influences body heat stability and curd formation in dairy beverages.'),
    ('Caseinate', 'milk', 'Caseinate is a soluble milk protein ingredient made from casein and used to increase body emulsification and protein content.'),
    ('Churning', 'milk', 'Churning is vigorous agitation that destabilizes cream fat globules until they cluster and separate into butter grains and buttermilk.'),
    ('Coagulation', 'milk', 'Coagulation is the aggregation of milk proteins into a gel or curd through acid enzymes heat or salts.'),
    ('Colostrum', 'milk', 'Colostrum is the first milk produced after birth and it is rich in antibodies proteins and bioactive compounds.'),
    ('Creaming', 'milk', 'Creaming is the upward movement of milk fat during standing that creates a richer top layer.'),
    ('Creamline', 'milk', 'Creamline describes milk that develops a visible fat layer at the top because the product has not been homogenized.'),
    ('Culturing', 'milk', 'Culturing is the inoculation of milk with selected microbes to develop acidity flavor texture and preservation.'),
    ('Curd', 'milk', 'Curd is the coagulated milk solids formed when proteins set through acid heat or rennet during dairy processing.'),
    ('Curdling', 'milk', 'Curdling is visible milk protein separation caused by acid heat age or instability that forms clumps and released liquid.'),
    ('Feedlot', 'milk', 'A feedlot is an intensive animal feeding operation and it is less associated with fluid milk production than specialized dairies.'),
    ('Foaming', 'milk', 'Foaming is the incorporation of air into milk which creates bubbles and changes texture volume and drink presentation.'),
    ('Gelation', 'milk', 'Gelation is the formation of a continuous protein network that gives dairy beverages or cultured products body and set texture.'),
    ('Guernsey', 'milk', 'Guernsey is a dairy cattle breed known for flavorful milk with elevated butterfat and a naturally golden hue.'),
    ('Holstein', 'milk', 'Holstein is a dairy cattle breed known for high milk yield and relatively lower butterfat and protein concentration.'),
    ('Homogenization', 'milk', 'Homogenization is the pressure process that breaks milk fat into smaller droplets to improve stability texture and uniform appearance.'),
    ('Jersey', 'milk', 'Jersey is a dairy cattle breed valued for milk with comparatively high butterfat protein and rich yellow color.'),
    ('Kefir', 'milk', 'Kefir is a fermented milk drink made with bacteria and yeasts that produce acidity light effervescence and complex flavor.'),
    ('Laban', 'milk', 'Laban is a traditional fermented milk beverage common in the Middle East with a savory acidic and refreshing profile.'),
    ('Lactase', 'milk', 'Lactase is the enzyme that splits lactose into glucose and galactose to improve sweetness and digestibility in lactose reduced milk beverages.'),
    ('Lactation', 'milk', 'Lactation is the physiological period when a mammal produces milk and its stage affects dairy composition and yield.'),
    ('Lactose', 'milk', 'Lactose is milk''s primary sugar and it contributes mild sweetness browning potential and fermentation substrate in dairy drinks.'),
    ('Lipolysis', 'milk', 'Lipolysis is the breakdown of milk fat into fatty acids which can create rancid or sharp flavors.'),
    ('Mastitis', 'milk', 'Mastitis is inflammation of the udder that can alter milk quality composition flavor and processing performance.'),
    ('Microfiltration', 'milk', 'Microfiltration is membrane processing that removes bacteria spores and larger particles from milk while retaining most dissolved components.'),
    ('Milkshed', 'milk', 'Milkshed is the geographic area that supplies raw milk to a processor dairy plant or beverage market.'),
    ('Ovine', 'milk', 'Ovine means derived from sheep and it describes milk or dairy products made from sheep milk.'),
    ('Pasteurizer', 'milk', 'A pasteurizer is equipment that heats milk under controlled time and temperature conditions to reduce pathogens and spoilage microbes.'),
    ('Probiotic', 'milk', 'Probiotic describes live microorganisms added at effective levels to support a health benefit when delivered in a dairy beverage.'),
    ('Proteolysis', 'milk', 'Proteolysis is the breakdown of milk proteins into peptides and amino acids during processing storage or fermentation.'),
    ('Rennet', 'milk', 'Rennet is an enzyme preparation that coagulates casein and is used mainly in cheese making and some cultured dairy applications.'),
    ('Separation', 'milk', 'Separation is centrifugal processing that divides milk into cream and skim portions based on density differences.'),
    ('Silage', 'milk', 'Silage is fermented preserved forage used as dairy feed and it can influence milk aroma when poorly managed.'),
    ('Skimming', 'milk', 'Skimming is the removal of some or most milk fat to produce lower fat dairy beverages.'),
    ('Syneresis', 'milk', 'Syneresis is the expulsion of liquid from a protein gel and it appears as whey separation in cultured dairy products.'),
    ('Texturization', 'milk', 'Texturization is the adjustment of dairy structure and mouthfeel through processing ingredients or protein interactions.'),
    ('Thermization', 'milk', 'Thermization is a mild heat treatment used to reduce microbial load in raw milk before further processing.'),
    ('Uht', 'milk', 'UHT is ultra high temperature processing that commercially sterilizes milk for extended shelf life in unopened aseptic packaging.'),
    ('Ultraheat', 'milk', 'Ultraheat is very high temperature treatment used to rapidly lower microbial risk and extend dairy beverage shelf life.'),
    ('Whey', 'milk', 'Whey is the liquid fraction remaining after milk coagulates and it contains water lactose whey proteins minerals and some fat.'),
    ('Yogurt', 'milk', 'Yogurt is a cultured milk product fermented mainly by thermophilic bacteria until it develops acidity body and a clean tart flavor.'),
    ('Absinthe', 'spirits', 'Absinthe is a high proof anise-flavored spirit traditionally distilled with botanicals such as wormwood fennel and green anise.'),
    ('Agricole', 'spirits', 'Agricole refers to rum made directly from fresh sugarcane juice rather than from molasses.'),
    ('Aguardiente', 'spirits', 'Aguardiente is a broad term for strong distilled spirits in Spanish-speaking regions, often made from sugarcane and sometimes flavored with anise.'),
    ('Alambic', 'spirits', 'An alambic is a traditional pot still, usually made of copper, used for batch distillation of spirits.'),
    ('Aquavit', 'spirits', 'Aquavit is a Scandinavian distilled spirit flavored primarily with caraway or dill and other botanicals.'),
    ('Arak', 'spirits', 'Arak is a distilled spirit from the eastern Mediterranean or parts of Asia, commonly flavored with anise.'),
    ('Armagnac', 'spirits', 'Armagnac is a French grape brandy from Gascony, typically distilled once in a continuous still and aged in oak.'),
    ('Azeotrope', 'spirits', 'An azeotrope is a liquid mixture that boils and condenses at a constant composition, limiting separation by ordinary distillation.'),
    ('Backset', 'spirits', 'Backset is the acidic liquid left in a still after distillation, reused in some mashes to control fermentation and flavor.'),
    ('Batching', 'spirits', 'Batching is the practice of combining ingredients or spirit lots in measured quantities before further processing, proofing, or service.'),
    ('Bottling', 'spirits', 'Bottling is the stage where finished spirit is filled into retail containers under controlled proof, volume, and closure conditions.'),
    ('Brandy', 'spirits', 'Brandy is a spirit distilled from wine or other fermented fruit juice and often matured in oak.'),
    ('Cachaca', 'spirits', 'Cachaca is a Brazilian cane spirit distilled from fermented fresh sugarcane juice rather than molasses.'),
    ('Calvados', 'spirits', 'Calvados is an apple or pear brandy from Normandy, France, produced under regulated regional standards.'),
    ('Charcoal', 'spirits', 'Charcoal is carbonized wood used in some spirits production for filtration or mellowing by removing selected compounds.'),
    ('Congeners', 'spirits', 'Congeners are minor alcohols acids esters and other compounds formed during fermentation and aging that influence aroma and flavor.'),
    ('Curacao', 'spirits', 'Curacao is an orange-flavored liqueur traditionally made with dried laraha peel and a neutral or brandy base.'),
    ('Demerara', 'spirits', 'Demerara in spirits usually refers to rum associated with Guyana, historically linked to sugar from the Demerara region.'),
    ('Distillate', 'spirits', 'Distillate is the condensed liquid collected from a still after vaporization and separation during distillation.'),
    ('Distillation', 'spirits', 'Distillation is the process of separating and concentrating alcohol and aroma compounds by heating vaporizing and condensing a fermented liquid.'),
    ('Dunder', 'spirits', 'Dunder is the spent wash from rum distillation, sometimes reused to support fermentation and develop heavier flavor compounds.'),
    ('EauDeVie', 'spirits', 'Eau de vie is an unaged fruit spirit distilled to preserve the character of the source fruit.'),
    ('Evaporation', 'spirits', 'Evaporation is the loss of water alcohol or both from a spirit during storage, especially while aging in wood.'),
    ('Feints', 'spirits', 'Feints are late-run spirit fractions from distillation that contain heavier compounds and are often recycled into later runs.'),
    ('Fusel', 'spirits', 'Fusel refers to higher alcohols produced during fermentation and distillation that can add heaviness or harshness in excess.'),
    ('Gin', 'spirits', 'Gin is a distilled spirit whose predominant flavor comes from juniper, often supported by other botanicals.'),
    ('Grappa', 'spirits', 'Grappa is an Italian pomace spirit distilled from the skins seeds and stems left after winemaking.'),
    ('Heads', 'spirits', 'Heads are the first usable distillation fractions after foreshots, containing lighter volatile compounds such as aldehydes and esters.'),
    ('Hearts', 'spirits', 'Hearts are the central distillation cut containing the cleanest and most desirable balance of alcohol and flavor compounds.'),
    ('Highproof', 'spirits', 'Highproof describes a spirit bottled or measured at a relatively elevated alcohol strength compared with standard expressions.'),
    ('Juniper', 'spirits', 'Juniper is the berry-like botanical whose piney resinous character defines the core flavor of gin.'),
    ('Kirsch', 'spirits', 'Kirsch is a clear cherry eau de vie distilled from fermented cherries, including their stones in many traditional methods.'),
    ('Liqueur', 'spirits', 'Liqueur is a sweetened flavored spirit made by blending or redistilling alcohol with botanicals fruit dairy or other ingredients.'),
    ('Macerate', 'spirits', 'To macerate is to soak botanicals fruit or other materials in liquid so flavor color and aroma compounds extract.'),
    ('Maturation', 'spirits', 'Maturation is the period in which a spirit develops through time in cask or other storage, gaining integration and complexity.'),
    ('Mezcal', 'spirits', 'Mezcal is a Mexican agave spirit made from cooked agave hearts, fermented and distilled, often with smoky or earthy notes.'),
    ('Moonshine', 'spirits', 'Moonshine commonly refers to illegally produced or informally made unaged distilled spirit, especially whiskey or other grain spirits.'),
    ('Newmake', 'spirits', 'New make is freshly distilled spirit before maturation, showing the raw character of fermentation and distillation.'),
    ('Nosing', 'spirits', 'Nosing is the professional evaluation of a spirit''s aroma by smelling it carefully to assess character intensity and faults.'),
    ('Overproof', 'spirits', 'Overproof describes a spirit bottled above the standard strength for its category, typically well above 40 percent alcohol by volume.'),
    ('Peated', 'spirits', 'Peated describes malt or a resulting spirit that carries smoky phenolic character from exposure to peat smoke.'),
    ('Potstill', 'spirits', 'A pot still is a batch distillation apparatus that generally produces a more characterful spirit than highly rectifying continuous stills.'),
    ('Proofing', 'spirits', 'Proofing is the controlled dilution of spirit with water to reach a target bottling strength.'),
    ('Rectification', 'spirits', 'Rectification is repeated vapor-liquid separation within distillation that increases purity or alcoholic strength by removing less desired compounds.'),
    ('Rhum', 'spirits', 'Rhum is the French term commonly used for rum from French-speaking regions, especially styles tied to cane juice production.'),
    ('Rye', 'spirits', 'Rye in spirits refers to the grain used in mash bills, valued for adding spicy herbal and dry flavor notes.'),
    ('Solera', 'spirits', 'Solera is an aging and fractional blending system where younger spirit replenishes older stocks across tiers of barrels.'),
    ('Sourmash', 'spirits', 'Sour mash is a whiskey production method that adds spent stillage to fresh mash to stabilize pH and fermentation.'),
    ('Stillage', 'spirits', 'Stillage is the liquid and solid residue left in a still after distillation has removed alcohol vapor.'),
    ('Stripping', 'spirits', 'Stripping is the first distillation run that concentrates alcohol from wash into low wines without making final cut decisions.'),
    ('Sugarcane', 'spirits', 'Sugarcane is the tropical grass whose juice or molasses provides fermentable sugar for rum and other cane spirits.'),
    ('Tails', 'spirits', 'Tails are the late distillation fractions rich in heavier oils and less volatile compounds, often recycled or discarded.'),
    ('Tequila', 'spirits', 'Tequila is a Mexican spirit made from blue agave and produced under denomination rules in designated regions.'),
    ('Tincture', 'spirits', 'A tincture is a concentrated alcoholic extract of botanicals or other flavoring materials used for blending or seasoning spirits.'),
    ('Vermouth', 'spirits', 'Vermouth is a fortified and aromatized wine flavored with botanicals, commonly used in cocktails and aperitif service.'),
    ('Washback', 'spirits', 'A washback is the vessel where wort or wash ferments into alcoholic liquid before distillation.'),
    ('Whiskey', 'spirits', 'Whiskey is a distilled spirit made from fermented grain mash and usually matured in wooden casks.'),
    ('Wormtub', 'spirits', 'A worm tub is a traditional condenser in which a coiled vapor tube cools in water to condense spirit.'),
    ('Anji', 'tea', 'Anji usually refers to Anji Baicha a Chinese green tea from Zhejiang made from a pale-leaf cultivar with fresh sweet chestnut notes.'),
    ('Assam', 'tea', 'Assam is a strong black tea style and origin from northeastern India known for malty body full flavor and good performance with milk.'),
    ('Astringent', 'tea', 'Astringent describes the drying puckering mouthfeel caused mainly by polyphenols binding with proteins in saliva.'),
    ('Autumnal', 'tea', 'Autumnal means relating to fall harvest conditions and often describes teas made from later-season growth.'),
    ('Baihao', 'tea', 'Baihao means white down and refers to fine leaf hairs or to teas visibly rich in silvery buds.'),
    ('Baimudan', 'tea', 'Baimudan or White Peony is a white tea style made from bud-and-leaf plucks with a fuller body than silver needle.'),
    ('Bancha', 'tea', 'Bancha is a later-harvest Japanese green tea generally made from more mature leaves and offering a simpler lower-aroma everyday cup.'),
    ('Baozhong', 'tea', 'Baozhong is a lightly oxidized strip-style oolong from Taiwan known for floral fragrance clarity and gentle body.'),
    ('Benifuki', 'tea', 'Benifuki is a Japanese tea cultivar often used for black tea and specialized green teas because of its aromatic and chemical profile.'),
    ('Biluochun', 'tea', 'Biluochun is a Chinese green tea of tightly curled leaves known for early spring tenderness pronounced aroma and fruity floral character.'),
    ('Briskness', 'tea', 'Briskness is a lively bright palate sensation in tea combining freshness structure and a clean quick finish.'),
    ('Camellia', 'tea', 'Camellia refers to Camellia sinensis the evergreen plant species whose leaves and buds are used to make true tea.'),
    ('Catechin', 'tea', 'Catechin is a major tea polyphenol that contributes bitterness astringency and antioxidant chemistry especially in less oxidized teas.'),
    ('Ceylon', 'tea', 'Ceylon is the traditional trade name for tea from Sri Lanka with styles ranging from bright citrusy high-grown lots to fuller low-grown teas.'),
    ('Clonal', 'tea', 'Clonal describes tea plants propagated from cuttings of one parent so a field expresses more uniform traits.'),
    ('Compression', 'tea', 'Compression is the pressing of finished tea into cakes bricks or other shapes for aging storage and transport.'),
    ('Ctc', 'tea', 'CTC means crush tear curl a machine process that makes small uniform pellets for fast strong and consistent infusion.'),
    ('Cultivar', 'tea', 'A cultivar is a cultivated plant selection maintained for stable traits such as yield aroma leaf shape seasonality or disease tolerance.'),
    ('Dahongpao', 'tea', 'Dahongpao is a celebrated Wuyi rock oolong known for heavy roast mineral depth and long layered aftertaste.'),
    ('Darjeeling', 'tea', 'Darjeeling is tea grown in the Darjeeling district of India and is prized for layered floral aroma lively acidity and delicate structure.'),
    ('Dianhong', 'tea', 'Dianhong is Yunnan black tea typically made from large-leaf cultivars and valued for honeyed sweetness cocoa notes and golden buds.'),
    ('Firing', 'tea', 'Firing is the application of heat to stop enzyme activity reduce moisture and stabilize finished tea for storage.'),
    ('Flush', 'tea', 'A flush is a distinct seasonal growth cycle of new tea shoots and the harvest taken from that growth.'),
    ('Gaba', 'tea', 'Gaba tea is processed in low-oxygen conditions to increase gamma aminobutyric acid and often shows fruity smooth low-astringency character.'),
    ('Genmaicha', 'tea', 'Genmaicha is Japanese tea blended with toasted rice creating a savory nutty aroma that softens grassy green tea notes.'),
    ('Gyokuro', 'tea', 'Gyokuro is a premium Japanese shaded green tea with high umami sweetness dense body and a low-temperature brewing style.'),
    ('Hojicha', 'tea', 'Hojicha is a roasted Japanese tea usually made from bancha or sencha and known for brown color low bitterness and toasty aroma.'),
    ('Jasmine', 'tea', 'Jasmine tea is tea scented with jasmine blossoms so the finished cup carries floral aroma without requiring added syrupy flavoring.'),
    ('Kabusecha', 'tea', 'Kabusecha is Japanese green tea shaded for a shorter period than gyokuro giving a cup between sencha brightness and gyokuro umami.'),
    ('Keemun', 'tea', 'Keemun is a Chinese black tea from Qimen county known for elegant fragrance soft texture and notes often described as cocoa fruit or orchid.'),
    ('Kukicha', 'tea', 'Kukicha is a Japanese tea composed mainly of stems stalks and twigs producing a light sweet cup with mild vegetal character.'),
    ('Lapsang', 'tea', 'Lapsang usually means Lapsang Souchong a black tea traditionally smoke-dried over pine wood for a distinct resinous smoky aroma.'),
    ('Liquor', 'tea', 'Liquor is the brewed tea itself meaning the liquid in the cup rather than the dry leaf.'),
    ('Longjing', 'tea', 'Longjing or Dragon Well is a pan-fired Chinese green tea recognized for flat leaves gentle roast and nutty chestnut-like flavor.'),
    ('Matcha', 'tea', 'Matcha is finely milled powdered tea made from tencha and whisked into water so the drinker consumes the whole leaf.'),
    ('Monsoonal', 'tea', 'Monsoonal means influenced by seasonal monsoon weather which can strongly affect tea growth rate chemistry and cup profile.'),
    ('Muscatel', 'tea', 'Muscatel describes a grape-like aroma and flavor note classically associated with some second flush Darjeeling teas.'),
    ('Nilgiri', 'tea', 'Nilgiri is tea from the Blue Mountains of southern India and is often valued for clean fragrance brisk liquor and reliable iced tea performance.'),
    ('Orthodox', 'tea', 'Orthodox describes traditional tea manufacture using rolling and shaping methods that preserve more whole leaf character than CTC processing.'),
    ('Osmanthus', 'tea', 'Osmanthus tea is tea scented or blended with osmanthus flowers to add a sweet apricot-like floral aroma.'),
    ('Oxidative', 'tea', 'Oxidative describes reactions between tea compounds and oxygen during processing that darken leaves and change aroma and flavor.'),
    ('Panfiring', 'tea', 'Panfiring is dry heat treatment in a hot pan or drum used to fix green tea and create toasted notes.'),
    ('Plucking', 'tea', 'Plucking is the harvest step where workers or machines remove selected buds and leaves according to the intended tea style.'),
    ('Polyphenol', 'tea', 'Polyphenol is a broad class of plant compounds in tea that shape bitterness astringency color and oxidation behavior.'),
    ('Puerh', 'tea', 'Puerh is a post-processed tea from Yunnan that can be aged or ripened and is often compressed for storage and trade.'),
    ('Roasting', 'tea', 'Roasting is a later heat treatment used to deepen aroma reduce grassy notes and add toast nut or caramelized character.'),
    ('Rolling', 'tea', 'Rolling is the shaping step that twists or breaks tea leaves to influence appearance extraction and enzymatic exposure.'),
    ('Saemidori', 'tea', 'Saemidori is a Japanese cultivar valued for vivid green color early budding and sweet umami-rich liquor.'),
    ('Sencha', 'tea', 'Sencha is the standard Japanese steamed green tea style with needle-shaped leaves and a flavor profile balancing sweetness umami bitterness and fresh green notes.'),
    ('Sheng', 'tea', 'Sheng is the raw style of pu erh that starts relatively fresh and bitter and develops deeper complexity through aging.'),
    ('Shincha', 'tea', 'Shincha means new tea and refers to the earliest seasonal Japanese tea shipments prized for freshness sweetness and vivid aroma.'),
    ('Shou', 'tea', 'Shou is the ripened style of pu erh produced through accelerated pile fermentation to create dark color mellow body and earthy notes.'),
    ('Shoumei', 'tea', 'Shoumei is a later-picked white tea made from more mature leaves and usually gives a darker fuller and less delicate cup.'),
    ('Steaming', 'tea', 'Steaming is a heat-fixation method that halts oxidation quickly and preserves bright green color and marine vegetal notes.'),
    ('Steeping', 'tea', 'Steeping is the act of soaking tea in water for a chosen time and temperature to extract flavor aroma and texture.'),
    ('Tamaryokucha', 'tea', 'Tamaryokucha is a Japanese green tea with curled leaves and a softer rounder profile than typical straight-needle sencha.'),
    ('Tencha', 'tea', 'Tencha is shaded Japanese tea processed without final rolling and primarily used as the raw material for matcha.'),
    ('Terpene', 'tea', 'A terpene is an aromatic plant compound that contributes floral citrus piney or herbal notes to tea aroma.'),
    ('Theanine', 'tea', 'Theanine is an amino acid in tea associated with sweetness savory character and a smoother less harsh cup.'),
    ('Tieguanyin', 'tea', 'Tieguanyin is a famous oolong tea style and cultivar associated with Anxi and noted for floral aroma and a smooth textured cup.'),
    ('Tippy', 'tea', 'Tippy describes tea rich in unopened buds or tips which often contribute delicacy sweetness and visible golden or silvery leaf accents.'),
    ('Vernal', 'tea', 'Vernal means relating to spring and in tea usually describes spring growth harvest timing or flavor character.'),
    ('Withering', 'tea', 'Withering is the controlled reduction of leaf moisture after harvest to soften texture and prepare leaves for shaping or oxidation.'),
    ('Wuyi', 'tea', 'Wuyi refers to the mountainous Fujian region that produces yancha or rock oolong teas with mineral structure and roasted complexity.'),
    ('Yabukita', 'tea', 'Yabukita is the dominant Japanese tea cultivar because it combines good yield cold tolerance and a balanced familiar flavor profile.'),
    ('Yunnan', 'tea', 'Yunnan is a tea-producing province in southwestern China known for large-leaf material used in black tea green tea and pu erh.'),
    ('Alkalinity', 'water', 'The water''s capacity to neutralize acids mainly from bicarbonate and carbonate ions which can soften perceived sharpness on the palate.'),
    ('Aquifer', 'water', 'An underground layer of permeable rock or sediment that stores and transmits water and often shapes a source''s mineral signature.'),
    ('Arsenic', 'water', 'A toxic trace element that may occur naturally in groundwater and is tightly limited for drinking water safety.'),
    ('Artesian', 'water', 'Water from a confined aquifer where natural pressure causes it to rise in a well or outlet.'),
    ('Bicarbonate', 'water', 'A major dissolved ion that buffers acidity and strongly affects alkalinity texture and the way water carries flavor.'),
    ('Brackish', 'water', 'Water with salinity between freshwater and seawater often requiring treatment before it is pleasant or suitable to drink.'),
    ('Calcium', 'water', 'A common mineral cation that contributes hardness supports structure and can give water a firmer more tactile palate.'),
    ('Catchment', 'water', 'The surface area where precipitation is collected and directed toward a reservoir spring or other water source.'),
    ('Chloride', 'water', 'A dissolved anion that can make water seem rounder sweeter and fuller while excessive levels taste salty.'),
    ('Chlorination', 'water', 'A disinfection method using chlorine compounds to control microbes and provide residual protection in the water.'),
    ('Conductivity', 'water', 'An electrical measure that estimates dissolved ion content and is often used as a quick indicator of mineral concentration.'),
    ('Desalination', 'water', 'The removal of dissolved salts from seawater or brackish water to produce water suitable for drinking.'),
    ('Disinfection', 'water', 'The treatment step used to inactivate harmful microorganisms so water remains microbiologically safe through packaging or distribution.'),
    ('Fluoride', 'water', 'A naturally occurring or adjusted mineral ion monitored closely because it affects potability and regulatory compliance.'),
    ('Glacial', 'water', 'A source descriptor for water originating from melt or ancient ice systems often marketed for purity and low contamination.'),
    ('Groundwater', 'water', 'Water stored beneath the surface in soil and rock formations and commonly used for bottled and municipal supply.'),
    ('Hardness', 'water', 'A measure of dissolved calcium and magnesium that influences texture scale formation and how firmly water feels in the mouth.'),
    ('Hydrogeology', 'water', 'The study of groundwater within geologic formations focusing on flow chemistry recharge and aquifer behavior.'),
    ('Hydrology', 'water', 'The science of water movement distribution and storage across the atmosphere land surface and subsurface.'),
    ('Iron', 'water', 'A trace metal that can lend rusty metallic flavors and staining even at relatively low concentrations.'),
    ('Magnesium', 'water', 'A hardness mineral that can add grip freshness and a slightly bitter edge when present at notable levels.'),
    ('Manganese', 'water', 'A trace metal that can cause metallic notes discoloration and technical issues when concentrations rise above desirable levels.'),
    ('Membrane', 'water', 'A selective filtration barrier used in processes such as reverse osmosis to remove salts particles and microbes.'),
    ('Mineralization', 'water', 'The total load and balance of dissolved minerals that define a water''s structure taste persistence and pairing behavior.'),
    ('Nitrate', 'water', 'An oxidized nitrogen compound whose elevated concentration signals contamination risk and can disqualify water for safe drinking.'),
    ('Nitrite', 'water', 'A reactive nitrogen compound usually found at very low levels and treated as a serious contamination indicator.'),
    ('Ozonation', 'water', 'A treatment method using ozone gas to oxidize contaminants and disinfect water without leaving a lasting residual.'),
    ('Palatability', 'water', 'The overall sensory acceptability of water based on cleanliness balance texture temperature and absence of off flavors.'),
    ('Potability', 'water', 'The condition of water being safe and acceptable for drinking under health standards and sensory expectations.'),
    ('Potassium', 'water', 'A dissolved mineral present in smaller amounts that may slightly round palate feel without strongly defining most waters.'),
    ('Purity', 'water', 'A general quality concept describing freedom from unwanted contaminants though it does not by itself guarantee sensory character.'),
    ('Recharge', 'water', 'The process by which surface water infiltrates soil and replenishes an aquifer or groundwater reserve.'),
    ('Remineralization', 'water', 'The post-treatment addition or restoration of minerals to adjust stability mouthfeel and flavor after intensive purification.'),
    ('Runoff', 'water', 'Water from rain or melt that flows over land surfaces and can carry sediments nutrients and pollutants into supply.'),
    ('Salinity', 'water', 'The concentration of dissolved salts that shapes taste density and suitability for drinking or culinary use.'),
    ('Silica', 'water', 'Dissolved silicon compounds that are often associated with a silky texture and softer mouthfeel in certain waters.'),
    ('Sodium', 'water', 'A dissolved cation that can broaden texture and subtly enhance sweetness while high levels may taste distinctly saline.'),
    ('Softness', 'water', 'A sensory impression or analytical condition of low mineral hardness giving water a gentler texture and less chalky structure.'),
    ('Sparkling', 'water', 'Water containing dissolved carbon dioxide that creates effervescence lift and a more pointed tactile profile.'),
    ('Springwater', 'water', 'Water collected from an underground formation that flows naturally to the surface or is tapped at the spring.'),
    ('Stillwater', 'water', 'Water served without carbonation offering a quieter texture and a clearer view of mineral balance.'),
    ('Sulfate', 'water', 'An anion that can accentuate dryness bitterness and linear finish especially when calcium or magnesium sulfate is prominent.'),
    ('Ultraviolet', 'water', 'A nonchemical disinfection process that uses UV light to damage microbial DNA as water passes the treatment chamber.'),
    ('Watershed', 'water', 'The land area that drains into a shared water body and influences source quality through geology vegetation and land use.'),
    ('Aglianico', 'wine', 'Southern Italian black grape producing deeply colored wines with high tannin firm acidity and strong aging potential.'),
    ('Albarino', 'wine', 'Aromatic white grape grown especially in Atlantic Iberia that yields high-acid wines with citrus stone fruit and saline notes.'),
    ('Amarone', 'wine', 'Dry powerful red wine from Valpolicella made from partially dried grapes to concentrate flavor extract and alcohol.'),
    ('Ampelography', 'wine', 'The study and identification of grapevines through leaf cluster shoot berry morphology and genetic traits.'),
    ('Appellation', 'wine', 'A legally defined geographic designation governing where grapes are grown and often how a wine is produced and labeled.'),
    ('Assemblage', 'wine', 'The blending of base wines grape varieties vineyards or lots to create a final wine with intended balance and style.'),
    ('Astringency', 'wine', 'A drying gripping mouthfeel caused mainly by phenolic compounds binding with salivary proteins during tasting.'),
    ('Autolysis', 'wine', 'The breakdown of dead yeast cells after fermentation or tirage contributing bread dough texture and savory complexity.'),
    ('Barbera', 'wine', 'Italian black grape known for deep color modest tannin and naturally high acidity that supports vibrant fruit-driven wines.'),
    ('Barolo', 'wine', 'Nebbiolo-based red DOCG from Piedmont noted for pale color firm tannin high acidity and long aging capacity.'),
    ('Barrique', 'wine', 'Small oak barrel usually about 225 liters used for maturation and oak influence through controlled oxygen exposure.'),
    ('Biodynamic', 'wine', 'A farming system treating the vineyard as a self-sustaining organism using compost preparations and a lunar-based calendar.'),
    ('Blanc', 'wine', 'French term meaning white used in wine names to indicate a white wine or white juice component.'),
    ('Bobal', 'wine', 'Spanish black grape valued for color acidity and tannin often producing robust reds and deeply pigmented rose wines.'),
    ('Botrytis', 'wine', 'Noble rot caused by Botrytis cinerea that dehydrates ripe grapes and intensifies sweetness acidity and aromatic complexity.'),
    ('Bourgogne', 'wine', 'French name for Burgundy and also the regional appellation for wines produced under its broadest AOC rules.'),
    ('Brix', 'wine', 'Scale measuring sugar in grape juice or must as approximate grams of sugar per 100 grams of solution.'),
    ('Brunello', 'wine', 'Local name for Sangiovese Grosso and shorthand for the long-lived Tuscan red made entirely from it.'),
    ('Cabernet', 'wine', 'A vineyard or label reference usually meaning Cabernet Sauvignon though it can also denote Cabernet Franc depending on context.'),
    ('Carbonic', 'wine', 'Short for carbonic maceration which is intracellular fermentation in a carbon dioxide-rich vessel emphasizing fruit and low tannin.'),
    ('Carignan', 'wine', 'Productive Mediterranean black grape that can yield savory high-acid reds with firm tannin when cropped for concentration.'),
    ('Carmenere', 'wine', 'Late-ripening Bordeaux variety now associated with Chile producing deeply colored wines with dark fruit herbs and soft tannins.'),
    ('Chablis', 'wine', 'Chardonnay from the northern Burgundy district of Chablis often defined by high acidity restrained fruit and chalky minerality.'),
    ('Champagne', 'wine', 'Traditional-method sparkling wine from Champagne produced under strict regional rules and typically blended for consistency and complexity.'),
    ('Chaptalization', 'wine', 'Addition of sugar to grape must before or during fermentation to raise potential alcohol without increasing ripeness.'),
    ('Clone', 'wine', 'A genetically selected vine population propagated from one parent vine to preserve specific agronomic and flavor traits.'),
    ('Decanting', 'wine', 'Transferring wine from bottle to another vessel to separate sediment or increase oxygen exposure before service.'),
    ('Dosage', 'wine', 'Liqueur d expedition added after disgorgement in traditional-method sparkling wine to set the final sweetness level.'),
    ('Elegance', 'wine', 'A tasting term for a wine whose balance texture length and detail convey refinement rather than sheer power.'),
    ('Extraction', 'wine', 'The transfer of color tannin flavor and other compounds from grape solids into juice or wine during production.'),
    ('Filtration', 'wine', 'Mechanical clarification that removes suspended particles and sometimes microbes before bottling to improve stability and brightness.'),
    ('Fining', 'wine', 'Clarification process using reactive agents such as bentonite or egg white to remove specific unwanted compounds.'),
    ('Fronsac', 'wine', 'Right Bank Bordeaux appellation producing mostly Merlot-based reds from clay and limestone slopes west of Libourne.'),
    ('Gamay', 'wine', 'Black grape best known from Beaujolais producing light to medium-bodied wines with bright acidity and red fruit.'),
    ('Grenache', 'wine', 'Warm-climate black grape with high sugar potential that gives generous alcohol ripe fruit and relatively modest color.'),
    ('Harvest', 'wine', 'The picking of grapes at chosen ripeness based on sugar acidity phenolic development health and intended wine style.'),
    ('Hermitage', 'wine', 'Northern Rhone appellation producing ageworthy Syrah-based reds and limited Marsanne Roussanne whites from a granitic hill.'),
    ('Jeroboam', 'wine', 'Large-format bottle whose capacity varies by wine type but commonly equals three liters for still wine.'),
    ('Jura', 'wine', 'Cool eastern French region known for distinctive wines including Savagnin-based oxidative styles and delicate reds from local varieties.'),
    ('Lambrusco', 'wine', 'Italian sparkling wine category made from Lambrusco grapes and produced in styles ranging from dry to sweet.'),
    ('Languedoc', 'wine', 'Large Mediterranean region in southern France producing broad volumes of red rose white and sparkling wines.'),
    ('Lees', 'wine', 'Deposits of spent yeast and other solids remaining after fermentation that can influence texture and flavor during aging.'),
    ('Maceration', 'wine', 'Contact time between juice and grape skins and often seeds or stems to extract color tannin and flavor.'),
    ('Malbec', 'wine', 'Black grape from southwest France and Argentina that can produce deeply colored wines with plum fruit and tannic structure.'),
    ('Malolactic', 'wine', 'Refers to malolactic fermentation in which bacteria convert sharper malic acid into softer lactic acid and carbon dioxide.'),
    ('Marsanne', 'wine', 'Northern Rhone white grape giving medium to full-bodied wines with moderate acidity and notes of orchard fruit and wax.'),
    ('Merlot', 'wine', 'Black grape valued for plush texture moderate acidity and dark fruit profile often used to soften structured blends.'),
    ('Minerality', 'wine', 'Tasting term suggesting stony saline or chalk-like impressions in a wine rather than a directly measurable flavor compound.'),
    ('Monastrell', 'wine', 'Spanish name for Mourvedre which yields deeply colored savory wines with tannin warmth and Mediterranean herb character.'),
    ('Mourvedre', 'wine', 'Late-ripening black grape producing structured savory wines with dark fruit earth spice and frequent gamey notes.'),
    ('Muscadet', 'wine', 'Light high-acid white wine from the western Loire made from Melon de Bourgogne and often aged on lees.'),
    ('Muscat', 'wine', 'Large family of aromatic grapes used for still sparkling and fortified wines with pronounced floral and grapey perfume.'),
    ('Nebbiolo', 'wine', 'Piedmontese black grape producing pale yet powerful wines marked by high tannin high acidity and complex perfume.'),
    ('Oenology', 'wine', 'The science and practice of winemaking including fermentation maturation stabilization packaging and sensory evaluation.'),
    ('Oxidation', 'wine', 'Chemical reaction with oxygen that can develop complexity in some wines or cause browning and freshness loss in others.'),
    ('Parellada', 'wine', 'Catalan white grape used mainly in Cava for finesse acidity and delicate citrus floral character.'),
    ('Pigeage', 'wine', 'Punching down the cap of skins during red fermentation to submerge solids and moderate extraction.'),
    ('Pinot', 'wine', 'Family name most often referring to Pinot Noir though it also includes related grapes such as Pinot Gris and Pinot Blanc.'),
    ('Pomerol', 'wine', 'Prestigious Right Bank Bordeaux appellation dominated by Merlot and known for supple texture and plush depth.'),
    ('Primitivo', 'wine', 'Southern Italian black grape genetically equivalent to Zinfandel and known for ripe fruit and elevated alcohol.'),
    ('Pumpover', 'wine', 'Fermentation technique that draws juice from the bottom of a tank and sprays it over the cap for extraction.'),
    ('Racking', 'wine', 'Moving wine off lees or sediment into a clean vessel to clarify it and manage reduction or oxygen exposure.'),
    ('Reduction', 'wine', 'Limited-oxygen condition that can preserve freshness or create sulfur-derived aromas such as struck flint or rubber.'),
    ('Reserva', 'wine', 'Iberian labeling term indicating wines that meet legally defined aging periods and sometimes higher production standards.'),
    ('Riesling', 'wine', 'High-acid aromatic white grape capable of expressing site clearly across styles from bone dry to lusciously sweet.'),
    ('Ripasso', 'wine', 'Valpolicella wine refermented on Amarone or Recioto pomace to gain color body tannin and flavor depth.'),
    ('Rondinella', 'wine', 'Verona grape commonly blended in Valpolicella for color disease resistance and contribution to dried-grape wines.'),
    ('Sangiovese', 'wine', 'Italy''s most planted premium black grape known for sour cherry notes firm acidity and adaptable regional expression.'),
    ('Sauternes', 'wine', 'Sweet Bordeaux appellation where botrytized Semillon Sauvignon Blanc and Muscadelle produce intensely concentrated wines.'),
    ('Sommelier', 'wine', 'Wine service professional responsible for beverage selection cellar management guest guidance and proper service standards.'),
    ('Syrah', 'wine', 'Northern Rhone and global black grape producing deeply colored wines with dark fruit pepper and firm structure.'),
    ('Tannin', 'wine', 'Phenolic compound from skins seeds stems and oak that contributes bitterness structure and ageworthy grip.'),
    ('Tempranillo', 'wine', 'Spain''s signature black grape producing savory structured wines with red fruit tobacco and moderate acidity.'),
    ('Teroldego', 'wine', 'Alpine black grape from Trentino producing deeply colored wines with dark fruit brisk acidity and rustic tannin.'),
    ('Torrontes', 'wine', 'Highly aromatic Argentine white grape that offers floral perfume but usually finishes dry with fresh acidity.'),
    ('Trebbiano', 'wine', 'Large family of Italian white grapes generally valued for yield acidity and neutral profile rather than strong aroma.'),
    ('Typicity', 'wine', 'Degree to which a wine shows the expected character of its grape origin region or style.'),
    ('Vendange', 'wine', 'French word for grape harvest and by extension the act or period of picking.'),
    ('Veraison', 'wine', 'Onset of ripening when grapes soften accumulate sugar and change color from green to their mature hue.'),
    ('Verdelho', 'wine', 'White grape associated with Madeira and Australia producing wines with citrus fruit firm acidity and moderate body.'),
    ('Vermentino', 'wine', 'Mediterranean white grape known for bright acidity herbal citrus notes and a saline almond-toned finish.'),
    ('Vintage', 'wine', 'The year in which the grapes for a wine were harvested and often shorthand for that season''s conditions.'),
    ('Viognier', 'wine', 'Aromatic white grape yielding full-bodied wines with stone fruit floral notes and typically modest acidity.'),
    ('Viscosity', 'wine', 'Apparent thickness of a wine in the glass influenced mainly by alcohol sugar extract and temperature.'),
    ('Volatile', 'wine', 'In wine usage usually shorthand for volatile acidity which is the portion of acidity that readily evaporates.'),
    ('Zinfandel', 'wine', 'Black grape widely grown in California producing ripe fruit-driven wines with generous alcohol and spice.')
)
update public.terminology_entries as t
set
  meaning = d.meaning,
  reference_links = rs.reference_links,
  mla_citations = rs.mla_citations,
  source_title = rs.source_title,
  source_authors = rs.source_authors,
  purchase_links = rs.purchase_links,
  is_verbatim_from_source = false,
  source_rights_basis = rs.source_rights_basis,
  source_note = rs.source_note
from defs as d
cross join reference_shelf as rs
where t.term = d.term
  and t.beverage_type = d.beverage_type;
